apiVersion: v1
name: gocd
home: https://www.gocd.org/
version: 2.17.1
appVersion: 25.4.0
description: GoCD is an open-source continuous delivery server to model and visualize complex workflows with ease.
icon: https://gocd.github.io/assets/images/go-icon-black-192x192.png
keywords:
  - gocd
  - ci
  - cd
  - ci/cd
  - continuous-integration
  - continuous-delivery
  - continuous-deployment
  - continuous-testing
sources:
  - https://github.com/gocd/gocd/tree/25.4.0
  - https://github.com/gocd/helm-chart/tree/gocd-2.17.1/gocd
maintainers:
  - name: chadlwilson
    email: chad.lee.wilson@gmail.com
  - name: arvindsv
    email: arvind@thoughtworks.com
annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: integration-delivery
  artifacthub.io/images: |
    - name: gocd-server
      image: docker.io/gocd/gocd-server:25.4.0
      platforms:
        - linux/amd64
        - linux/arm64
    - name: gocd-agent-wolfi (optional)
      image: docker.io/gocd/gocd-agent-wolfi:25.4.0
      platforms:
        - linux/amd64
        - linux/arm64
