apiVersion: v1
name: gocd
home: https://www.gocd.org/
version: 2.13.0
appVersion: 25.1.0
description: GoCD is an open-source continuous delivery server to model and visualize complex workflows with ease.
icon: https://gocd.github.io/assets/images/go-icon-black-192x192.png
keywords:
- gocd
- ci
- cd
- ci/cd
- continuous-integration
- continuous-delivery
- continuous-deployment
- continuous-testing
sources:
- https://github.com/gocd/gocd
maintainers:
- name: chadlwilson
  email: chadw@thoughtworks.com
- name: arvindsv
  email: arvind@thoughtworks.com
